type='FAIR1M_1_5'
source_fair_dataset_path='/root/autodl-tmp/oriented-rcnn/DOTA/data'
source_dataset_path='/root/autodl-tmp/oriented-rcnn/DOTA/dota'
target_dataset_path='/root/autodl-tmp/oriented-rcnn/DOTA/preprocessed_without_ms'
convert_tasks=['train','test']

# available labels: train, val, test, trainval
tasks=[
    dict(
        label='train',
        config=dict(
            subimage_size=1024,
            overlap_size=512,
            multi_scale=[1.0],
            horizontal_flip=False,
            vertical_flip=False,
            rotation_angles=[0.] 
        )
    ),
    dict(
        label='test',
        config=dict(
            subimage_size=1024,
            overlap_size=512,
            multi_scale=[1.0],
            horizontal_flip=False,
            vertical_flip=False,
            rotation_angles=[0.] 
        )
    )
]