common:
    workers: 4

    num_points: 5000
    num_classes: 337 #BU3DFE:100 Bosphorus:105 FRGC:466 KinectLow: 337
    batch_size: 22
    
    base_lr: 0.001   # 0.001
    lr_clip: 0.00001
    lr_decay: 0.7   # 0.7
    decay_step: 20 #21
    epochs: 400  # 180

    weight_decay: 0.0001
    bn_momentum: 0.9
    bnm_clip: 0.01
    bn_decay: 0.5
    
    evaluate: 1
    val_freq_epoch: 1   # frequency in epoch for validation, can be decimal
    print_freq_iter: 40   # frequency in iteration for printing infomation
    
    input_channels: 3     # feature channels except (x, y, z)
    
    # h_ij: 0  for 3D Euclidean distance (3D Ed),    channels = 1
    #       1  for (3D Ed, x_i, x_j, x_j - x_i),     channels = 10
    #       2  for (2D Ed, x'_i, x'_j, x'_j - x'_i), channels = 10,  x' indicates 2D coordinates
    relation_prior: 1
    
    checkpoint: "cls/face_id_Kinect_4SA_4Attention_DoubleModules_nonorconcat/total86.47_cls_ssn_iter_286812_loss_0.544506_PositiveMulti_Cos0.30.pth"   # the model to start from
    save_path: cls/face_id_Kinect_4SA_4Attention_DoubleModules_nonorconcat/ # cls/face_id_BU3DFE
    data_root: /data2/yangjunpeng/Workspace/pointnet.pytorch/3d_dataset/
