name: p2rnet
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2022.4.26
  - certifi=2021.5.30
  - cudatoolkit=11.1.74
  - dataclasses=0.8
  - ffmpeg=4.3
  - freetype=2.11.0
  - gmp=6.2.1
  - gnutls=3.6.15
  - intel-openmp=2022.0.1
  - jpeg=9b
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.3
  - nettle=3.7.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1p
  - pillow=8.3.1
  - pip=21.2.2
  - python=3.6.13
  - pytorch=1.8.1
  - readline=8.1.2
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.38.5
  - tk=8.6.12
  - torchvision=0.9.1
  - typing_extensions=4.1.1
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
    - absl-py==1.1.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - attrs==21.4.0
    - cached-property==1.5.2
    - cachetools==4.2.4
    - charset-normalizer==2.0.12
    - frozenlist==1.2.0
    - google-auth==2.9.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - h5py==3.1.0
    - idna==3.3
    - idna-ssl==1.1.0
    - importlib-metadata==4.8.3
    - markdown==3.3.7
    - multidict==5.2.0
    - numpy-quaternion==2022.4.2
    - oauthlib==3.2.0
    - opencv-python==4.0.0.21
    - pandas==1.1.5
    - plyfile==0.7.4
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pytz==2022.1
    - pyyaml==6.0
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - seaborn==0.11.2
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - trimesh==3.12.7
    - urllib3==1.26.10
    - vtk==9.1.0
    - werkzeug==2.0.3
    - wslink==1.6.6
    - yarl==1.7.2
    - zipp==3.6.0
