python ../../train.py dataset/caption_data/caption_stage1_train.tsv,dataset/caption_data/caption_val.tsv\
--selected-cols=0,4,2
--bpe-dir=utils/BPE
--user-dir=ofa_module
--restore-file=checkpoints/ofa_base.pt
--reset-optimizer --reset-dataloader --reset-meters
--save-dir=/public16_data/wjh/OFA-main/run_scripts/caption/stage1_checkpoints/1_0.06_6000/
--task=caption
--arch=ofa_base
--criterion=adjust_label_smoothed_cross_entropy
--label-smoothing=0.1
--batch-size=16
--update-freq=4
--encoder-normalize-before
--decoder-normalize-before
--share-decoder-input-output-embed
--share-all-embeddings
--layernorm-embedding
--patch-layernorm-embedding
--code-layernorm-embedding
--resnet-drop-path-rate=0.0
--encoder-drop-path-rate=0.1
--decoder-drop-path-rate=0.1
--dropout=0.1
--attention-dropout=0.0
--weight-decay=0.01 --optimizer=adam --adam-betas="(0.9,0.999)" --adam-eps=1e-08 --clip-norm=1.0
--lr-scheduler=polynomial_decay --lr=1e-5
--max-epoch=1
--warmup-ratio=0.06
--log-format=simple --log-interval=10
--fixed-validation-seed=7
--no-epoch-checkpoints --keep-best-checkpoints=1
--save-interval=1 --validate-interval=1
--save-interval-updates=500 --validate-interval-updates=500
--eval-cider
--eval-cider-cached-tokens=/public16_data/wjh/OFA-main/dataset/caption_data/cider_cached_tokens/coco-valid-words.p
--eval-args="{beam:5,max_len_b:16,no_repeat_ngram_size:3}"
--best-checkpoint-metric=cider --maximize-best-checkpoint-metric
--max-src-length=80
--max-tgt-length=20
--find-unused-parameters
--freeze-encoder-embedding
--freeze-decoder-embedding
--add-type-embedding
--scale-attn
--scale-fc
--scale-heads
--disable-entangle
--num-bins=1000
--patch-image-size=480
--drop-worst-ratio=0.2
--drop-worst-after=6000
--fp16
--fp16-scale-window=512
--num-workers=0
