# default values
root = '/pycharm/RM_DeepRL'
algo = 'dqn'
workload = 'jobs.csv'
beta = 0.5
iteration = 2000
fixed_episodic_reward = 10000
epsilon = 0.001
learning_rate = 0.001
gamma = 0.9
placement_penalty = 30
pp_apply = 'false'
